use_frameworks!

platform :ios, '9.0'

target 'JKMonitor_Example' do
  pod 'JKMonitor', :path => '../'

  target 'JKMonitor_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
